// src/components/footer.tsx
const LINKS = [
  { name: "GitHub", href: "https://github.com/ElbertePlinio" },
  { name: "X", href: "https://x.com/ElbertePlinio" },
  { name: "LinkedIn", href: "https://www.linkedin.com/in/ElbertePlinio/" },
  { name: "Pickforge", href: "https://pickforge.dev" },
];

export function Footer() {
  return (
    <footer className="border-t border-line">
      <div className="mx-auto flex max-w-6xl flex-col gap-6 px-6 py-10 sm:flex-row sm:items-center sm:justify-between">
        <p className="text-sm text-muted">© 2026 Elberte Plínio</p>
        <nav className="flex flex-wrap gap-6">
          {LINKS.map((link) => (
            <a
              key={link.name}
              href={link.href}
              target="_blank"
              rel="noopener noreferrer"
              className="text-sm text-muted transition-colors hover:text-foreground"
            >
              {link.name}
            </a>
          ))}
        </nav>
      </div>
    </footer>
  );
}

// src/lib/components/Footer.svelte
<script lang="ts">
  import Heart from '$lib/icons/Heart.svelte';
</script>

<footer class="border-t border-purple-700 px-4 py-6">
  <div class="mx-auto flex max-w-7xl flex-col items-center justify-center md:flex-row">
    <p class="mb-4 text-sm text-purple-400 md:mb-0">
      &copy; {new Date().getFullYear()} - Made with 
      <Heart size={14} color="#ef4444" className="inline-block" /> 
      by Elberte Plínio.
    </p>
    <!-- Uncomment if needed
    <div class="flex space-x-6">
      <a href="/terms" class="text-sm text-purple-400 transition-colors hover:text-white"
        >Terms of Service</a
      >
      <a href="/privacy" class="text-sm text-purple-400 transition-colors hover:text-white"
        >Privacy</a
      >
    </div>
    -->
  </div>
</footer>
